name: Bundlewatch

on: [push]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ steps.check.outputs.BUNDLEWATCH_GITHUB_TOKEN }}
    steps:
      - run: >
          echo "::set-output name=BUNDLEWATCH_GITHUB_TOKEN::${{ env.BUNDLEWATCH_GITHUB_TOKEN != '' }}";
        id: check
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

  bundlewatch:
    needs: ["secrets"]
    if: >
      needs.secrets.outputs.BUNDLEWATCH_GITHUB_TOKEN == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci --ignore-scripts
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          NEXT_TELEMETRY_DISABLED: 1
