name: Lint

on: [push]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci --ignore-scripts
      - uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_args: "--ignore-path .gitignore"
          prettier: true
          prettier_args: "--ignore-path .gitignore"
          stylelint: true
          stylelint_args: "--ignore-path .gitignore"
          check_name: Lint
