name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts
      - run: npm run lint:eslint

  stylelint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts
      - run: npm run lint:stylelint

  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --ignore-scripts
      - run: npm run lint:prettier
