name: Relative ci

on: [push]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository_owner == 'ismay' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci --ignore-scripts
      - run: npm run build
        env:
          ANALYZE_BUNDLE: "enabled"
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
