name: Test

on: [push]

jobs:
  secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      PERCY_TOKEN: ${{ steps.check.outputs.PERCY_TOKEN }}
    steps:
      - run: >
          echo "::set-output name=PERCY_TOKEN::${{ env.PERCY_TOKEN != '' }}";
        id: check
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --ignore-scripts
      - run: npm run test:unit

  e2e:
    needs: ["secrets"]
    if: >
      needs.secrets.outputs.PERCY_TOKEN == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm run dev:mocked
          wait-on: "npx wait-on -s 1 http://localhost:3000"
          config-file: .cypress/cypress.json
          command-prefix: "percy exec -- npx"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          NEXT_TELEMETRY_DISABLED: 1
