name: Test

on: [push]

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci --ignore-scripts
      - run: npm run test:unit

  e2e:
    if: github.repository_owner == 'ismay' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: "npx wait-on -s 1 http://localhost:3000"
          config-file: .cypress/cypress.json
          command-prefix: "percy exec -- npx"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          NEXT_TELEMETRY_DISABLED: 1
          API_MOCKING: "enabled"
